# Netlify configuration file
# See https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"